// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARvRikqTIMxQAmY-TBZOcBMT4Br5lpnWg',
    appId: '1:383168505049:web:611df07e950f55feb88ac8',
    messagingSenderId: '383168505049',
    projectId: 'esp-8622-c27e0',
    authDomain: 'esp-8622-c27e0.firebaseapp.com',
    storageBucket: 'esp-8622-c27e0.appspot.com',
    measurementId: 'G-X34KN3ZEL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqUU3aq5C1kFQ07C5QCzqumGtC72aabdI',
    appId: '1:383168505049:android:adeb712f31016e53b88ac8',
    messagingSenderId: '383168505049',
    projectId: 'esp-8622-c27e0',
    storageBucket: 'esp-8622-c27e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbM8hkbqufi4QUBd8UqfeSpB5V6_izU4A',
    appId: '1:383168505049:ios:f0726aa46307f45eb88ac8',
    messagingSenderId: '383168505049',
    projectId: 'esp-8622-c27e0',
    storageBucket: 'esp-8622-c27e0.appspot.com',
    iosBundleId: 'com.example.esp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbM8hkbqufi4QUBd8UqfeSpB5V6_izU4A',
    appId: '1:383168505049:ios:f0726aa46307f45eb88ac8',
    messagingSenderId: '383168505049',
    projectId: 'esp-8622-c27e0',
    storageBucket: 'esp-8622-c27e0.appspot.com',
    iosBundleId: 'com.example.esp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARvRikqTIMxQAmY-TBZOcBMT4Br5lpnWg',
    appId: '1:383168505049:web:4c23358632643839b88ac8',
    messagingSenderId: '383168505049',
    projectId: 'esp-8622-c27e0',
    authDomain: 'esp-8622-c27e0.firebaseapp.com',
    storageBucket: 'esp-8622-c27e0.appspot.com',
    measurementId: 'G-7WQE64XP2T',
  );
}
